### ISSUE TITLE
Can't compile dll

### ISSUE THREAD

**Issue by filipovskis** [danielga/gmcl_speech#1]
![изображение](https://user-images.githubusercontent.com/48033052/103800977-c0155d80-5055-11eb-838e-f94628b5202d.png)

**Comment by filipovskis** [comment]
I built a dll using gmcommon generator v1, other versions have errors, so I can't build x64 dll.

**Comment by danielga** [comment]
Updated the master branch to include multiple fixes and get rid of the Microsoft Speech Platform SDK. Tested with both project generator v2 and v3 and x86 and x86-64. Didn't test the module ingame however.
