### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vety010** [danielga/gmcl_speech#2]
So i tried my best at understanding the code but did not succeed. Yes, maybe its skill issue or something like that but could you explain how do i get recognized string? I need to make a system where user asks something in voice chat and the game does something based on what user said (e.g.: "equip weapon 4 2" - the game equips 2nd weapon from 4th slot).

**Comment by vety010** [comment]
So uh i actually wrote a lil' bit more of the module so now it totally supports strings, but if there was an easier way around i'd still like to know about it

**Comment by danielga** [comment]
I suppose I never truly finished this module and it's been too long. From a cursory glance at the speech recognition documentation, it seems you'd need to use [`CSpEvent`](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ee431916(v=vs.85)) on the result of [`GetEvents`](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ee450799(v=vs.85)).
